version: '3.8'
services:
  node:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "8080:8080"
    networks:
      - backend-network
    environment:
      - DB_HOST= host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network
    ports:
      - "80:80"
    depends_on:
      - node

networks:
  backend-network:
    driver: bridge
